kind: Secret
apiVersion: v1
metadata:
  name: {{ include "microcks.name" . }}-mongodb-connection
  labels:
    {{- include "microcks.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.mongodb.username }}
  password: {{ .Values.mongodb.password }}
  {{- if .Values.mongodb.adminPassword }}
  adminPassword: {{ .Values.mongodb.adminPassword | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 40 | quote }}
  {{- end }}
type: kubernetes.io/basic-auth
