pgsql:
  service: service-registry-db
  database: apicurio
  user: apicurio
  password: apicurio

route:
  enabled: true
  host: 
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

ingress:
  disabled: true
